### ISSUE TITLE
[Bug]: I'm unable to install the plugin

### ISSUE THREAD

**Issue by YousufSSyed** [chrisgrieser/obsidian-smarter-paste#2]
### Bug Description

The plugin does not show up in the community plugins section, after unzipping in the release file and moving it to the plugins folder in my vault, or by installing it with BRAT (by pasting the repo URL there).

### Text **before** pasting it into Obsidian.

N/A

### Text **after** pasting it into Obsidian.

N/A

### Where the text was copied from

N/A

### Obsidian Version

1.1.9

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
oh sorry, I forgot to archive this repo. The complete functionality of this plugin has already been sherlocked (implemented) by the Linter plugin. You can install it, and find the respective features under the pasting section: https://github.com/platers/obsidian-linter#paste-rules
